import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/ui/modeToggler";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "AskGPT",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
			<ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
					<ModeToggle />
          {children} <Toaster />
        </ThemeProvider>
			</body>
		</html>
	);
}
